version: '3'
services:
  web:
    image: tovend # Insert your own image name here
    environment:
      DATABASE_URL: postgres://anyusername:Password1@db/anydbname
      TEST_DATABASE_URL: postgres://anyusername:Password1@testdb/anydbname
    networks:
    - webnet
    links:
    - db
    ports:
    - 5000:5000
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: anyusername
      POSTGRES_DB: anydbname
      POSTGRES_PASSWORD: Password1
    networks:
    - webnet
  # I normally wouldn't do this, but if not your make tasks are failing
  # Could potentially consider stripping this out at some point!
  test_db: 
    image: postgres:alpine
    environment:
      POSTGRES_USER: anyusername
      POSTGRES_DB: anydbname
      POSTGRES_PASSWORD: Password1
    networks:
    - webnet
networks:
  webnet: